import { useState, useMemo, useEffect, useRef, useCallback } from 'react'
import { invoke, save as saveDialog, open as openDialog, readTextFile, writeTextFile, CmdResult, onScriptOutput, onScriptDone } from '../api/electron-bridge'
import {
  Play, Square, Save, Trash2, ArrowUp, ArrowDown,
  Plus, GripVertical, MousePointerClick, Hand, PenLine,
  Clock, AppWindow, Home, ChevronDown, FileCode, Loader,
  Copy, Edit3, Search, Filter, Download, Upload, History,
  Settings, Zap, Pause, SkipForward, RotateCcw
} from 'lucide-react'

interface Props {
  selectedDevice: string
  showNotif: (t: string, m: string) => void
}

// ===========================
// 操作类型定义
// ===========================
interface StepDef {
  type: string
  label: string
  icon: React.ReactNode
  color: string
  params: { key: string; label: string; placeholder: string; type: 'number' | 'text'; default?: string | number; min?: number; max?: number; required?: boolean }[]
  generate: (p: Record<string, string | number>) => string[]
  description?: string
}

const STEP_DEFS: StepDef[] = [
  {
    type: 'click',
    label: '点击 (Click)',
    icon: <MousePointerClick size={16} />,
    color: '#00d4ff',
    description: '模拟屏幕点击操作',
    params: [
      { key: 'x', label: 'X', placeholder: '540', type: 'number', default: 540, min: 0, required: true },
      { key: 'y', label: 'Y', placeholder: '960', type: 'number', default: 960, min: 0, required: true },
    ],
    generate: (p) => [
      `send_event touch press ${p.x} ${p.y}`,
      `sleep 0.1`,
      `send_event touch release`,
    ],
  },
  {
    type: 'slip',
    label: '滑动 (Slip)',
    icon: <Hand size={16} />,
    color: '#a855f7',
    description: '模拟屏幕滑动操作',
    params: [
      { key: 'x1', label: '起X', placeholder: '540', type: 'number', default: 540, min: 0, required: true },
      { key: 'y1', label: '起Y', placeholder: '1600', type: 'number', default: 1600, min: 0, required: true },
      { key: 'x2', label: '终X', placeholder: '540', type: 'number', default: 540, min: 0, required: true },
      { key: 'y2', label: '终Y', placeholder: '400', type: 'number', default: 400, min: 0, required: true },
    ],
    generate: (p) => [
      `send_event touch press ${p.x1} ${p.y1}`,
      `sleep 0.05`,
      `send_event touch slip ${p.x2} ${p.y2}`,
      `sleep 0.1`,
      `send_event touch release`,
    ],
  },
  {
    type: 'stylus',
    label: '扫描 (Stylus)',
    icon: <PenLine size={16} />,
    color: '#f59e0b',
    description: '模拟手写笔扫描操作',
    params: [
      { key: 'delay', label: '延迟(秒)', placeholder: '2', type: 'number', default: 2, min: 0.5, max: 10, required: true },
    ],
    generate: (p) => [
      `send_event camera press`,
      `sleep ${p.delay}`,
      `send_event camera release`,
    ],
  },
  {
    type: 'wait',
    label: '等待 (Wait)',
    icon: <Clock size={16} />,
    color: '#10b981',
    description: '等待指定秒数',
    params: [
      { key: 'seconds', label: '秒数', placeholder: '3', type: 'number', default: 3, min: 0.1, max: 300, required: true },
    ],
    generate: (p) => [`sleep ${p.seconds}`],
  },
  {
    type: 'openApp',
    label: '打开APP (OpenApp)',
    icon: <AppWindow size={16} />,
    color: '#ec4899',
    description: '启动指定的小程序',
    params: [
      { key: 'appId', label: 'APP ID', placeholder: '8080222437664451', type: 'text', default: '8080222437664451', required: true },
    ],
    generate: (p) => [`miniapp_cli start ${p.appId}`],
  },
  {
    type: 'home',
    label: '返回桌面 (Home)',
    icon: <Home size={16} />,
    color: '#64748b',
    description: '返回主界面',
    params: [],
    generate: () => [`miniapp_cli start 8080222437664451`],
  },
]

// ===========================
// 步骤数据类型
// ===========================
interface ScriptStep {
  id: string
  opType: string
  params: Record<string, string>
  enabled: boolean  // 是否启用该步骤
  createdAt: number // 创建时间戳
}

  // ===========================
  // 生成 shell 脚本（支持循环）
  // ===========================
  function generateShellScript(steps: ScriptStep[], loop: boolean = false): string {
    const lines: string[] = [
      '#!/bin/sh',  // 使用 sh 而非 bash
      '# Generated by ADB Tools Script Editor',
      '# 添加错误处理，确保脚本持续运行',
      'set +e  # 忽略错误，继续执行',
      '',
      `echo "=== Script Start: ${new Date().toLocaleString('zh-CN')} ==="`,
      '',
    ]
    
    if (loop) {
      lines.push('# 循环执行模式')
      lines.push('while true; do')
      lines.push('')
    }
    
    for (const step of steps) {
      if (!step.enabled) continue  // 跳过禁用的步骤
      const def = STEP_DEFS.find(d => d.type === step.opType)
      if (!def) continue
      lines.push(`  # ${def.label}`)
      const cmds = def.generate(step.params as Record<string, string | number>)
      // 为每个命令添加 || true，确保即使失败也继续
      lines.push(...cmds.map(cmd => `  ${cmd} || true`))
      lines.push('')
    }
    
    if (loop) {
      lines.push('  # 等待 1 秒后继续下一次循环')
      lines.push('  sleep 1')
      lines.push('done')
      lines.push('')
    }
    
    lines.push('echo "=== Script End ==="')
    return lines.join('\n')
  }

function getStepPreview(step: ScriptStep): string {
  const def = STEP_DEFS.find(d => d.type === step.opType)
  if (!def) return ''
  if (def.params.length === 0) return def.label
  const vals = def.params.map(p => String(step.params[p.key] || p.placeholder))
  return `${def.label}: ${vals.join(', ')}`
}

// ===========================
// 脚本模板
// ===========================
const SCRIPT_TEMPLATES = [
  {
    name: '快速启动测试',
    description: '打开APP -> 等待 -> 点击 -> 返回桌面',
    steps: [
      { opType: 'openApp', params: { appId: '8080222437664451' }, enabled: true },
      { opType: 'wait', params: { seconds: '2' }, enabled: true },
      { opType: 'click', params: { x: '300', y: '600' }, enabled: true },
      { opType: 'home', params: {}, enabled: true },
    ],
  },
  {
    name: '滑动浏览测试',
    description: '多次滑动操作模拟用户浏览',
    steps: [
      { opType: 'openApp', params: { appId: '8080222437664451' }, enabled: true },
      { opType: 'wait', params: { seconds: '1' }, enabled: true },
      { opType: 'slip', params: { x1: '300', y1: '800', x2: '300', y2: '200' }, enabled: true },
      { opType: 'wait', params: { seconds: '1' }, enabled: true },
      { opType: 'slip', params: { x1: '300', y1: '200', x2: '300', y2: '800' }, enabled: true },
      { opType: 'home', params: {}, enabled: true },
    ],
  },
  {
    name: '扫描测试',
    description: '模拟手写笔扫描操作',
    steps: [
      { opType: 'stylus', params: { delay: '2' }, enabled: true },
      { opType: 'wait', params: { seconds: '3' }, enabled: true },
      { opType: 'home', params: {}, enabled: true },
    ],
  },
]

// ===========================
// ScriptEditorPage 组件
// ===========================
export default function ScriptEditorPage({ selectedDevice, showNotif }: Props) {
  const [steps, setSteps] = useState<ScriptStep[]>(() => {
    // 从 localStorage 加载之前保存的步骤
    try {
      const stored = localStorage.getItem('adb_script_editor_current_steps')
      if (stored) {
        return JSON.parse(stored)
      }
    } catch {}
    return []
  })
  const [customName, setCustomName] = useState('测试')  // 自定义部分
  
  // 自动生成完整脚本名称: monkey-{自定义}-{时间戳}
  const scriptName = useMemo(() => {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5)
    return `monkey-${customName}-${timestamp}`
  }, [customName])
  const [selectedOpType, setSelectedOpType] = useState('click')
  const [paramValues, setParamValues] = useState<Record<string, string>>({})
  const [output, setOutput] = useState<Array<{ text: string; type: 'info' | 'error' | 'success'; timestamp: number }>>([])
  const [isRunning, setIsRunning] = useState(false)
  const [runningSerial, setRunningSerial] = useState('')
  const [enableLoop, setEnableLoop] = useState(false)  // 是否启用循环运行
  
  // 输出过滤和搜索
  const [outputFilter, setOutputFilter] = useState<'all' | 'error' | 'success'>('all')
  const [outputSearch, setOutputSearch] = useState('')
  
  // 批量选择状态
  const [selectedSteps, setSelectedSteps] = useState<Set<string>>(new Set())
  const [draggedStepId, setDraggedStepId] = useState<string | null>(null)  // 拖拽中的步骤ID

  // 保存的脚本列表（按设备 serial 隔离）
  const [savedScripts, setSavedScripts] = useState<Record<string, { name: string; steps: ScriptStep[] }[]>>({})
  const outputEndRef = useRef<HTMLDivElement>(null)

  // 加载保存的脚本列表
  useEffect(() => {
    try {
      const stored = localStorage.getItem('adb_script_editor_scripts')
      if (stored) setSavedScripts(JSON.parse(stored))
    } catch {}
  }, [])

  // 实时生成脚本预览
  const scriptPreview = useMemo(() => generateShellScript(steps, enableLoop), [steps, enableLoop])

  // 监听 script_output / script_done 事件
  useEffect(() => {
    const unsubOutput = onScriptOutput((data) => {
      if (data.serial !== selectedDevice) return
      const newLines: Array<{ text: string; type: 'info' | 'error' | 'success'; timestamp: number }> = (data.lines || []).map(line => ({
        text: line,
        type: (data.type === 'error' ? 'error' : 'info') as 'info' | 'error' | 'success',
        timestamp: Date.now(),
      }))
      setOutput(newLines)
      outputEndRef.current?.scrollIntoView({ behavior: 'smooth' })
    })
    const unsubDone = onScriptDone((data) => {
      if (data.serial !== selectedDevice) return
      const finalLines: Array<{ text: string; type: 'info' | 'error' | 'success'; timestamp: number }> = (data.lines || []).map(line => ({
        text: line,
        type: (data.code === 0 ? 'success' : 'error') as 'info' | 'error' | 'success',
        timestamp: Date.now(),
      }))
      setOutput(finalLines)
      setIsRunning(false)
      setRunningSerial('')
      if (data.code === 0) {
        showNotif('success', '脚本执行完成')
      } else {
        showNotif('warning', `脚本已终止，退出码: ${data.code}`)
      }
    })
    return () => {
      unsubOutput()
      unsubDone()
    }
  }, [selectedDevice])

  // ===========================
  // 添加步骤
  // ===========================
  const handleAddStep = () => {
    const def = STEP_DEFS.find(d => d.type === selectedOpType)!
    
    // 验证必填参数
    for (const param of def.params) {
      if (param.required && !paramValues[param.key]) {
        showNotif('warning', `请填写 ${param.label}`)
        return
      }
    }
    
    // 应用默认值
    const finalParams: Record<string, string> = {}
    for (const param of def.params) {
      if (paramValues[param.key]) {
        finalParams[param.key] = paramValues[param.key]
      } else if (param.default !== undefined) {
        finalParams[param.key] = String(param.default)
      }
    }
    
    const newStep: ScriptStep = {
      id: `${Date.now()}_${Math.random().toString(36).slice(2)}`,
      opType: selectedOpType,
      params: finalParams,
      enabled: true,
      createdAt: Date.now(),
    }
    setSteps(prev => [...prev, newStep])
    setParamValues({})
  }

  // ===========================
  // 删除步骤
  // ===========================
  const handleDeleteStep = (id: string) => {
    setSteps(prev => prev.filter(s => s.id !== id))
  }

  // ===========================
  // 复制步骤
  // ===========================
  const handleDuplicateStep = (step: ScriptStep) => {
    const newStep: ScriptStep = {
      ...step,
      id: `${Date.now()}_${Math.random().toString(36).slice(2)}`,
      createdAt: Date.now(),
    }
    const idx = steps.findIndex(s => s.id === step.id)
    setSteps(prev => {
      const next = [...prev]
      next.splice(idx + 1, 0, newStep)
      return next
    })
    showNotif('success', '步骤已复制')
  }

  // ===========================
  // 切换步骤启用状态
  // ===========================
  const handleToggleStep = (id: string) => {
    setSteps(prev => prev.map(s => 
      s.id === id ? { ...s, enabled: !s.enabled } : s
    ))
  }

  // ===========================
  // 批量删除选中步骤
  // ===========================
  const handleBatchDelete = () => {
    if (selectedSteps.size === 0) {
      showNotif('warning', '请先选择要删除的步骤')
      return
    }
    setSteps(prev => prev.filter(s => !selectedSteps.has(s.id)))
    setSelectedSteps(new Set())
    showNotif('success', `已删除 ${selectedSteps.size} 个步骤`)
  }

  // ===========================
  // 全选/取消全选
  // ===========================
  const handleSelectAll = () => {
    if (selectedSteps.size === steps.length) {
      setSelectedSteps(new Set())
    } else {
      setSelectedSteps(new Set(steps.map(s => s.id)))
    }
  }

  // ===========================
  // 切换单个步骤选择
  // ===========================
  const handleToggleSelect = (id: string) => {
    setSelectedSteps(prev => {
      const next = new Set(prev)
      if (next.has(id)) {
        next.delete(id)
      } else {
        next.add(id)
      }
      return next
    })
  }

  // ===========================
  // 拖拽排序
  // ===========================
  const handleDragStart = (e: React.DragEvent, id: string) => {
    setDraggedStepId(id)
    e.dataTransfer.effectAllowed = 'move'
    // 设置拖拽时的透明度
    setTimeout(() => {
      const element = document.getElementById(`step-${id}`)
      if (element) element.style.opacity = '0.5'
    }, 0)
  }

  const handleDragEnd = (e: React.DragEvent) => {
    setDraggedStepId(null)
    const element = document.getElementById(`step-${draggedStepId}`)
    if (element) element.style.opacity = '1'
  }

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault()
    e.dataTransfer.dropEffect = 'move'
  }

  const handleDrop = (e: React.DragEvent, targetId: string) => {
    e.preventDefault()
    if (!draggedStepId || draggedStepId === targetId) return
    
    setSteps(prev => {
      const dragIdx = prev.findIndex(s => s.id === draggedStepId)
      const dropIdx = prev.findIndex(s => s.id === targetId)
      if (dragIdx === -1 || dropIdx === -1) return prev
      
      const newSteps = [...prev]
      const [draggedItem] = newSteps.splice(dragIdx, 1)
      newSteps.splice(dropIdx, 0, draggedItem)
      return newSteps
    })
    
    setDraggedStepId(null)
  }

  // ===========================
  // 键盘快捷键支持
  // ===========================
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      // Ctrl/Cmd + S: 保存脚本
      if ((e.ctrlKey || e.metaKey) && e.key === 's') {
        e.preventDefault()
        handleSaveScript()
      }
      // Ctrl/Cmd + R: 运行脚本
      if ((e.ctrlKey || e.metaKey) && e.key === 'r' && !e.shiftKey) {
        e.preventDefault()
        if (!isRunning) handleRunScript()
      }
      // Escape: 停止脚本
      if (e.key === 'Escape' && isRunning) {
        e.preventDefault()
        handleStopScript()
      }
      // Delete: 删除选中步骤
      if (e.key === 'Delete' && selectedSteps.size > 0) {
        e.preventDefault()
        handleBatchDelete()
      }
    }

    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [selectedDevice, steps, isRunning, selectedSteps])

  // ===========================
  // 上移 / 下移
  // ===========================
  const handleMoveUp = (idx: number) => {
    if (idx === 0) return
    setSteps(prev => {
      const next = [...prev]
      ;[next[idx - 1], next[idx]] = [next[idx], next[idx - 1]]
      return next
    })
  }

  const handleMoveDown = (idx: number) => {
    setSteps(prev => {
      if (idx >= prev.length - 1) return prev
      const next = [...prev]
      ;[next[idx], next[idx + 1]] = [next[idx + 1], next[idx]]
      return next
    })
  }

  // ===========================
  // 保存脚本
  // ===========================
  const handleSaveScript = () => {
    if (!selectedDevice) { showNotif('warning', '请先连接设备'); return }
    if (steps.length === 0) { showNotif('warning', '脚本为空'); return }
    const serial = selectedDevice
    const newScripts = {
      ...savedScripts,
      [serial]: [
        ...(savedScripts[serial] || []).filter(s => s.name !== scriptName),
        { name: scriptName, steps },
      ],
    }
    setSavedScripts(newScripts)
    localStorage.setItem('adb_script_editor_scripts', JSON.stringify(newScripts))
    showNotif('success', `脚本 "${scriptName}" 已保存`)
  }

  // ===========================
  // 加载脚本
  // ===========================
  const handleLoadScript = (serial: string, name: string) => {
    const list = savedScripts[serial] || []
    const found = list.find(s => s.name === name)
    if (found) {
      setSteps(found.steps)
      // 从脚本名称中提取自定义部分（格式：monkey-{自定义}-{时间戳}）
      const parts = found.name.split('-')
      if (parts.length >= 3 && parts[0] === 'monkey') {
        // 提取自定义部分（去掉首尾的时间戳）
        const customPart = parts.slice(1, -2).join('-')
        setCustomName(customPart || '测试')
      } else {
        setCustomName('测试')
      }
      showNotif('success', `已加载脚本 "${name}"`)
    }
  }

  // ===========================
  // 删除脚本
  // ===========================
  const handleDeleteScript = (serial: string, name: string) => {
    const newScripts = {
      ...savedScripts,
      [serial]: (savedScripts[serial] || []).filter(s => s.name !== name),
    }
    setSavedScripts(newScripts)
    localStorage.setItem('adb_script_editor_scripts', JSON.stringify(newScripts))
    showNotif('success', `已删除脚本 "${name}"`)
  }

  // ===========================
  // 导出脚本文件
  // ===========================
  const handleExportScript = async () => {
    if (!selectedDevice) { showNotif('warning', '请先连接设备'); return }
    const path = await saveDialog({
      defaultPath: `${scriptName.replace(/\s+/g, '_')}_${Date.now()}.sh`,
      filters: [{ name: 'Shell Script', extensions: ['sh'] }],
    })
    if (!path) return
    try {
      // 脚本预览已经包含 shebang，直接保存
      await writeTextFile(path, scriptPreview)
      showNotif('success', `已导出到: ${path}`)
    } catch (e) {
      showNotif('error', String(e))
    }
  }

  // ===========================
  // 导入脚本文件
  // ===========================
  const handleImportScript = async () => {
    const path = await openDialog({
      filters: [{ name: 'Shell Script', extensions: ['sh', 'bash', 'txt'] }],
    })
    if (!path) return
    
    try {
      const content = await readTextFile(path)
      // 简单解析：从注释中提取步骤信息
      // 这里我们创建一个新脚本来保存原始内容
      setCustomName(`导入_${path.split('/').pop()?.split('.').shift() || '脚本'}`)
      showNotif('success', `已导入脚本文件`)
      // TODO: 更智能的解析逻辑可以将 shell 脚本转换为步骤
    } catch (e) {
      showNotif('error', `导入失败: ${String(e)}`)
    }
  }

  // ===========================
  // 清空所有步骤
  // ===========================
  const handleClearAll = () => {
    if (steps.length === 0) return
    setSteps([])
    setSelectedSteps(new Set())
    showNotif('success', '已清空所有步骤')
  }

  // ===========================
  // 加载模板
  // ===========================
  const handleLoadTemplate = (templateName: string) => {
    const template = SCRIPT_TEMPLATES.find(t => t.name === templateName)
    if (!template) return
    
    const newSteps: ScriptStep[] = template.steps.map((s, idx) => ({
      id: `${Date.now()}_${idx}_${Math.random().toString(36).slice(2)}`,
      opType: s.opType,
      params: Object.fromEntries(
        Object.entries(s.params).map(([k, v]) => [k, String(v)])
      ),
      enabled: s.enabled,
      createdAt: Date.now(),
    }))
    
    setSteps(newSteps)
    setCustomName(template.name)
    showNotif('success', `已加载模板: ${template.name}`)
  }

  // ===========================
  // 运行脚本（脱机后台执行）
  // ===========================
  const handleRunScript = async () => {
    if (!selectedDevice) { showNotif('warning', '请先连接设备'); return }
    if (steps.length === 0) { showNotif('warning', '脚本为空'); return }

    setOutput([])
    setIsRunning(true)
    setRunningSerial(selectedDevice)

    try {
      // 生成脚本文件名（使用 scriptName）
      const scriptFileName = `${scriptName}.sh`
      const scriptPath = `/data/${scriptFileName}`
      const logPath = `/data/${scriptName}.log`
      
      setOutput(prev => [...prev, { 
        text: `[信息] 正在推送脚本...`, 
        type: 'info' as const, 
        timestamp: Date.now() 
      }])
      
      // 将脚本内容写入设备
      // 使用 adb shell + cat heredoc 方式
      const writeCommand = `cat > ${scriptPath} << 'EOF'
${scriptPreview}
EOF`
      
      const writeResult = await invoke<any>('run_shell_command', { 
        serial: selectedDevice, 
        command: writeCommand,
        timeout: 10000
      })
      
      if (!writeResult?.success) {
        throw new Error(`写入脚本失败: ${writeResult?.error || '未知错误'}`)
      }
      
      setOutput(prev => [...prev, { 
        text: `[信息] 脚本内容已写入 (${scriptPreview.length} 字节)`, 
        type: 'info' as const, 
        timestamp: Date.now() 
      }, {
        text: `[调试] 写入结果: success=${writeResult.success}, output="${writeResult.stdout?.substring(0, 100) || ''}"`,
        type: 'info' as const,
        timestamp: Date.now()
      }])
      
      // 第2步：设置执行权限
      const chmodResult = await invoke<any>('run_shell_command', { 
        serial: selectedDevice, 
        command: `chmod 755 ${scriptPath}`
      })
      
      if (!chmodResult?.success) {
        throw new Error(`设置权限失败: ${chmodResult?.error || '未知错误'}`)
      }
      
      setOutput(prev => [...prev, { 
        text: `[信息] 执行权限已设置`, 
        type: 'info' as const, 
        timestamp: Date.now() 
      }])
      
      // 第3步：验证文件是否存在
      const verifyResult = await invoke<any>('run_shell_command', { 
        serial: selectedDevice, 
        command: `test -f ${scriptPath} && echo "FILE_EXISTS" || echo "FILE_NOT_FOUND"`,
        timeout: 5000
      })
      
      if (verifyResult?.success && verifyResult?.stdout === 'FILE_EXISTS') {
        setOutput(prev => [...prev, { 
          text: `[确认] 脚本文件验证通过`, 
          type: 'success' as const, 
          timestamp: Date.now() 
        }])
      } else {
        setOutput(prev => [...prev, { 
          text: `[警告] 无法验证脚本文件，但仍继续执行`, 
          type: 'error' as const, 
          timestamp: Date.now() 
        }, {
          text: `[调试] 验证结果: success=${verifyResult?.success}, output="${verifyResult?.stdout || ''}", error="${verifyResult?.error || '未知'}"`,
          type: 'info' as const,
          timestamp: Date.now()
        }])
      }
      
      // 第4步：在后台执行脚本（不阻塞）
      setOutput(prev => [...prev, { 
        text: `[信息] 正在启动脚本...`, 
        type: 'info' as const, 
        timestamp: Date.now() 
      }])
      
      // 使用专门的后台执行接口
      const bgResult = await invoke<any>('run_script_background', { 
        serial: selectedDevice,
        scriptPath: scriptPath,
        logPath: logPath
      })
      
      if (bgResult?.success) {
        // 显示日志文件大小
        const logSize = bgResult.logSize || 0
        const processRunning = bgResult.processRunning || false
        const logInfo = logSize > 0 ? ` | 日志大小: ${logSize} 字节` : ''
        const processInfo = processRunning ? ' | 进程运行中' : ' | ⚠ 进程未找到'
        
        setOutput(prev => [...prev, { 
          text: `[成功] ✓ 脚本已在后台运行${logInfo}${processInfo}`, 
          type: processRunning ? 'success' as const : 'error' as const,
          timestamp: Date.now() 
        }, {
          text: `[提示] 脚本路径: ${scriptPath}`,
          type: 'info' as const,
          timestamp: Date.now()
        }, {
          text: `[提示] 日志文件: ${logPath}`,
          type: 'info' as const,
          timestamp: Date.now()
        }, {
          text: `[提示] 查看日志: adb -s ${selectedDevice} shell tail -f ${logPath}`,
          type: 'info' as const,
          timestamp: Date.now()
        }, {
          text: `[提示] 停止脚本: adb -s ${selectedDevice} shell pkill -f ${scriptFileName}`,
          type: 'info' as const,
          timestamp: Date.now()
        }])
        
        if (processRunning) {
          showNotif('success', `脚本已成功启动: ${scriptFileName}`)
        } else {
          showNotif('warning', `脚本可能已退出，请检查日志`)
        }
      } else {
        throw new Error(`脚本启动失败: ${bgResult?.error || '未知错误'}`)
      }
      
    } catch (e) {
      setOutput(prev => [...prev, { text: `[错误] ${String(e)}`, type: 'error' as const, timestamp: Date.now() }])
      setIsRunning(false)
      setRunningSerial('')
      showNotif('error', `执行失败: ${String(e)}`)
    }
  }

  // ===========================
  // 停止脚本（停止后台运行的脚本）
  // ===========================
  const handleStopScript = async () => {
    if (!selectedDevice) return
    
    try {
      // 使用 pkill 停止后台运行的脚本进程
      const scriptFileName = `${scriptName}.sh`
      await invoke('run_shell_command', { 
        serial: selectedDevice, 
        command: `pkill -f ${scriptFileName}`
      })
      
      setIsRunning(false)
      setRunningSerial('')
      
      setOutput(prev => [...prev, 
        { text: '', type: 'info' as const, timestamp: Date.now() },
        { text: `--- 脚本已停止: ${scriptFileName} ---`, type: 'error' as const, timestamp: Date.now() }
      ])
      showNotif('warning', `脚本已停止: ${scriptFileName}`)
    } catch (e) {
      setOutput(prev => [...prev, { text: `[错误] 停止失败: ${String(e)}`, type: 'error' as const, timestamp: Date.now() }])
      showNotif('error', `停止失败: ${String(e)}`)
    }
  }

  // ===========================
  // 设备未选中
  // ===========================
  if (!selectedDevice) {
    return (
      <div className="empty-state">
        <div className="empty-icon"><FileCode size={48} /></div>
        <div className="empty-text">请先连接设备</div>
        <div className="empty-sub">脚本编辑需要在设备连接后使用</div>
      </div>
    )
  }

  const currentOpDef = STEP_DEFS.find(d => d.type === selectedOpType)!
  const deviceScripts = savedScripts[selectedDevice] || []

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', gap: 12, overflow: 'hidden' }}>

      {/* ===== 顶部：脚本名称 + 脚本管理 ===== */}
      <div style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}>
        <FileCode size={16} style={{ color: 'var(--accent-primary)', flexShrink: 0 }} />
        
        {/* 脚本名称显示 - monkey固定，自定义部分可编辑 */}
        <div style={{
          display: 'flex',
          alignItems: 'center',
          background: 'var(--bg-card)',
          border: '1px solid var(--border-color)',
          borderRadius: 8,
          padding: '6px 12px',
          fontSize: 13,
          gap: 4,
        }}>
          <span style={{ color: 'var(--text-muted)' }}>monkey-</span>
          <input
            type="text"
            value={customName}
            onChange={e => setCustomName(e.target.value)}
            placeholder="自定义"
            style={{
              background: 'transparent',
              border: 'none',
              borderBottom: '1px dashed var(--border-color)',
              color: 'var(--text-primary)',
              padding: '0 4px',
              fontSize: 13,
              width: 80,
              outline: 'none',
            }}
          />
          <span style={{ color: 'var(--text-muted)' }}>-{new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5)}</span>
        </div>

        {/* 脚本选择器 */}
        {deviceScripts.length > 0 && (
          <div style={{ display: 'flex', gap: 6, alignItems: 'center', flex: 1 }}>
            <select
              value=""
              onChange={e => { if (e.target.value) { const [s, n] = e.target.value.split('|'); handleLoadScript(s, n) } }}
              style={{
                background: 'var(--bg-card)',
                border: '1px solid var(--border-color)',
                borderRadius: 8,
                color: 'var(--text-primary)',
                padding: '6px 10px',
                fontSize: 12,
                outline: 'none',
                flex: 1,
                maxWidth: 220,
              }}
            >
              <option value="">— 加载已保存的脚本 —</option>
              {deviceScripts.map(s => (
                <option key={s.name} value={`${selectedDevice}|${s.name}`}>{s.name}</option>
              ))}
            </select>
          </div>
        )}

        <div style={{ display: 'flex', gap: 6, marginLeft: 'auto', alignItems: 'center' }}>
          {/* 循环运行开关 */}
          <label style={{ 
            display: 'flex', 
            alignItems: 'center', 
            gap: 6, 
            fontSize: 12, 
            color: 'var(--text-secondary)',
            cursor: 'pointer',
            userSelect: 'none',
          }}>
            <input
              type="checkbox"
              checked={enableLoop}
              onChange={e => setEnableLoop(e.target.checked)}
              style={{ cursor: 'pointer' }}
            />
            循环运行
          </label>
          
          <button className="btn btn-secondary" onClick={handleImportScript} title="从文件导入脚本">
            <Upload size={13} /> 导入
          </button>
          <button className="btn btn-secondary" onClick={handleSaveScript} title="保存到本地">
            <Save size={13} /> 保存
          </button>
          <button className="btn btn-secondary" onClick={handleExportScript} title="导出为 .sh 文件">
            <Download size={13} /> 导出
          </button>
          {steps.length > 0 && (
            <button className="btn btn-secondary" onClick={handleClearAll} title="清空所有步骤">
              <RotateCcw size={13} /> 清空
            </button>
          )}
          {isRunning ? (
            <button 
              className="btn" 
              style={{ background: 'var(--accent-error)', color: '#fff', display: 'flex', alignItems: 'center', gap: 4 }} 
              onClick={handleStopScript}
            >
              <Square size={13} fill="currentColor" /> 停止
            </button>
          ) : (
            <button className="btn btn-primary" onClick={handleRunScript}>
              <Play size={13} /> 运行
            </button>
          )}
        </div>
      </div>

      {/* ===== 主体：左右分栏 ===== */}
      <div style={{ display: 'flex', gap: 12, flex: 1, overflow: 'hidden' }}>

        {/* ----- 左侧：步骤编辑 ----- */}
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: 10, overflow: 'hidden' }}>

          {/* 模板快速加载 */}
          <div style={{
            background: 'var(--bg-card)',
            border: '1px solid var(--border-color)',
            borderRadius: 10,
            padding: 12,
          }}>
            <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 8, fontWeight: 600, letterSpacing: 1 }}>快速加载模板</div>
            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              {SCRIPT_TEMPLATES.map(template => (
                <button
                  key={template.name}
                  className="btn btn-secondary"
                  onClick={() => handleLoadTemplate(template.name)}
                  title={template.description}
                  style={{ padding: '6px 12px', fontSize: 11 }}
                >
                  <Zap size={12} /> {template.name}
                </button>
              ))}
            </div>
          </div>

          {/* 添加步骤区域 */}
          <div style={{
            background: 'var(--bg-card)',
            border: '1px solid var(--border-color)',
            borderRadius: 10,
            padding: 12,
          }}>
            <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 8, fontWeight: 600, letterSpacing: 1 }}>添加步骤</div>
            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'flex-end' }}>
              {/* 操作类型选择 */}
              <div>
                <select
                  value={selectedOpType}
                  onChange={e => { setSelectedOpType(e.target.value); setParamValues({}) }}
                  style={{
                    background: 'var(--bg-secondary)',
                    border: '1px solid var(--border-color)',
                    borderRadius: 8,
                    color: 'var(--text-primary)',
                    padding: '7px 10px',
                    fontSize: 12,
                    outline: 'none',
                    cursor: 'pointer',
                  }}
                >
                  {STEP_DEFS.map(def => (
                    <option key={def.type} value={def.type}>{def.label}</option>
                  ))}
                </select>
              </div>

              {/* 参数输入 - 横向排列 */}
              <div style={{ display: 'flex', gap: 8, alignItems: 'flex-end', flexWrap: 'wrap' }}>
                {currentOpDef.params.map(p => {
                  const value = paramValues[p.key] || ''
                  const hasError = p.required && !value
                  const isOutOfRange = p.type === 'number' && value && (
                    (p.min !== undefined && Number(value) < p.min) ||
                    (p.max !== undefined && Number(value) > p.max)
                  )
                  
                  return (
                    <div key={p.key} style={{ display: 'flex', flexDirection: 'row', alignItems: 'center', gap: 4 }}>
                      <label style={{ fontSize: 11, color: 'var(--text-muted)', whiteSpace: 'nowrap', minWidth: 'fit-content' }}>
                        {p.label}
                        {p.required && <span style={{ color: 'var(--accent-error)' }}>*</span>}
                      </label>
                      <input
                        type={p.type}
                        placeholder={p.placeholder}
                        value={value}
                        onChange={e => setParamValues(prev => ({ ...prev, [p.key]: e.target.value }))}
                        min={p.min}
                        max={p.max}
                        step={p.type === 'number' ? 0.1 : undefined}
                        title={isOutOfRange ? `范围: ${p.min ?? '-∞'}-${p.max ?? '+∞'}` : undefined}
                        style={{
                          background: hasError || isOutOfRange ? '#ff000015' : 'var(--bg-secondary)',
                          border: `1px solid ${hasError || isOutOfRange ? 'var(--accent-error)' : 'var(--border-color)'}`,
                          borderRadius: 6,
                          color: 'var(--text-primary)',
                          padding: '5px 8px',
                          fontSize: 11,
                          width: p.type === 'number' ? 70 : 120,
                          outline: 'none',
                        }}
                      />
                      {(hasError || isOutOfRange) && (
                        <span style={{ fontSize: 9, color: 'var(--accent-error)', whiteSpace: 'nowrap' }}>
                          {hasError ? '必填' : `${p.min ?? '-∞'}-${p.max ?? '+∞'}`}
                        </span>
                      )}
                    </div>
                  )
                })}

                <button className="btn btn-primary" onClick={handleAddStep} style={{ padding: '5px 12px', fontSize: 11 }}>
                  <Plus size={12} /> 添加
                </button>
              </div>
            </div>
          </div>

          {/* 步骤列表 */}
          <div style={{ flex: 1, overflow: 'auto', display: 'flex', flexDirection: 'column', gap: 6 }}>
            {steps.length === 0 ? (
              <div style={{
                textAlign: 'center',
                padding: '40px 20px',
                color: 'var(--text-muted)',
                fontSize: 13,
                border: '1px dashed var(--border-color)',
                borderRadius: 10,
              }}>
                点击上方「添加」将步骤加入脚本
              </div>
            ) : (
              <>
                {/* 批量操作工具栏 */}
                {selectedSteps.size > 0 && (
                  <div style={{
                    display: 'flex',
                    gap: 8,
                    alignItems: 'center',
                    padding: '8px 12px',
                    background: 'var(--bg-card)',
                    border: '1px solid var(--border-color)',
                    borderRadius: 8,
                  }}>
                    <span style={{ fontSize: 12, color: 'var(--text-secondary)' }}>
                      已选择 {selectedSteps.size} 个步骤
                    </span>
                    <button 
                      className="btn btn-secondary" 
                      onClick={handleBatchDelete}
                      style={{ padding: '4px 10px', fontSize: 11 }}
                    >
                      <Trash2 size={12} /> 删除选中
                    </button>
                    <button 
                      className="btn btn-secondary" 
                      onClick={() => setSelectedSteps(new Set())}
                      style={{ padding: '4px 10px', fontSize: 11 }}
                    >
                      取消选择
                    </button>
                  </div>
                )}

                {/* 全选按钮 */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0 4px' }}>
                  <button
                    onClick={handleSelectAll}
                    style={{
                      background: 'none',
                      border: 'none',
                      color: 'var(--text-muted)',
                      cursor: 'pointer',
                      fontSize: 11,
                      display: 'flex',
                      alignItems: 'center',
                      gap: 4,
                    }}
                  >
                    <input
                      type="checkbox"
                      checked={selectedSteps.size === steps.length && steps.length > 0}
                      onChange={handleSelectAll}
                      style={{ cursor: 'pointer' }}
                    />
                    全选
                  </button>
                  <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>
                    共 {steps.length} 个步骤
                  </span>
                </div>

                {steps.map((step, idx) => {
                  const def = STEP_DEFS.find(d => d.type === step.opType)!
                  const preview = def.generate(step.params as Record<string, string | number>).join(' && ')
                  const isSelected = selectedSteps.has(step.id)
                  
                  return (
                    <div 
                      key={step.id}
                      id={`step-${step.id}`}
                      draggable
                      onDragStart={(e) => handleDragStart(e, step.id)}
                      onDragEnd={handleDragEnd}
                      onDragOver={handleDragOver}
                      onDrop={(e) => handleDrop(e, step.id)}
                      style={{
                        background: isSelected ? 'var(--accent-primary)15' : 'var(--bg-card)',
                        border: `1px solid ${isSelected ? 'var(--accent-primary)' : 'var(--border-color)'}`,
                        borderRadius: 8,
                        padding: '8px 12px',
                        display: 'flex',
                        alignItems: 'center',
                        gap: 8,
                        opacity: step.enabled ? 1 : 0.5,
                        cursor: draggedStepId ? 'move' : 'default',
                        transition: 'opacity 0.2s, background 0.2s',
                      }}
                    >
                      {/* 选择框 */}
                      <input
                        type="checkbox"
                        checked={isSelected}
                        onChange={() => handleToggleSelect(step.id)}
                        onClick={(e) => e.stopPropagation()}
                        style={{ cursor: 'pointer', flexShrink: 0 }}
                      />

                      {/* 拖拽手柄 */}
                      <GripVertical size={14} style={{ color: 'var(--text-muted)', flexShrink: 0, cursor: 'grab' }} />

                      {/* 序号 */}
                      <span style={{
                        fontSize: 11,
                        color: 'var(--text-muted)',
                        background: 'var(--bg-secondary)',
                        borderRadius: 4,
                        padding: '2px 6px',
                        flexShrink: 0,
                        minWidth: 22,
                        textAlign: 'center',
                      }}>{idx + 1}</span>

                      {/* 操作类型标签 */}
                      <span style={{
                        fontSize: 11,
                        color: def.color,
                        background: def.color + '22',
                        borderRadius: 4,
                        padding: '2px 8px',
                        flexShrink: 0,
                        display: 'flex',
                        alignItems: 'center',
                        gap: 4,
                      }}>
                        {def.icon}
                        {def.label.split(' ')[0]}
                      </span>

                      {/* 命令预览 */}
                      <code style={{
                        flex: 1,
                        fontSize: 11,
                        color: 'var(--text-secondary)',
                        fontFamily: 'monospace',
                        overflow: 'hidden',
                        textOverflow: 'ellipsis',
                        whiteSpace: 'nowrap',
                      }}>{preview}</code>

                      {/* 操作按钮 */}
                      <div style={{ display: 'flex', gap: 2, flexShrink: 0 }}>
                        <button
                          onClick={() => handleToggleStep(step.id)}
                          title={step.enabled ? "禁用" : "启用"}
                          style={{
                            background: 'none',
                            border: 'none',
                            cursor: 'pointer',
                            color: step.enabled ? 'var(--accent-success)' : 'var(--text-muted)',
                            padding: '3px 5px',
                            borderRadius: 4,
                          }}
                        >
                          <Zap size={13} />
                        </button>
                        <button
                          onClick={() => handleDuplicateStep(step)}
                          title="复制"
                          style={{
                            background: 'none',
                            border: 'none',
                            cursor: 'pointer',
                            color: 'var(--text-secondary)',
                            padding: '3px 5px',
                            borderRadius: 4,
                          }}
                        >
                          <Copy size={13} />
                        </button>
                        <button
                          onClick={() => handleMoveUp(idx)}
                          disabled={idx === 0}
                          title="上移"
                          style={{
                            background: 'none', border: 'none', cursor: idx === 0 ? 'default' : 'pointer',
                            color: idx === 0 ? 'var(--text-muted)' : 'var(--text-secondary)',
                            padding: '3px 5px', borderRadius: 4,
                          }}
                        >
                          <ArrowUp size={13} />
                        </button>
                        <button
                          onClick={() => handleMoveDown(idx)}
                          disabled={idx === steps.length - 1}
                          title="下移"
                          style={{
                            background: 'none', border: 'none', cursor: idx === steps.length - 1 ? 'default' : 'pointer',
                            color: idx === steps.length - 1 ? 'var(--text-muted)' : 'var(--text-secondary)',
                            padding: '3px 5px', borderRadius: 4,
                          }}
                        >
                          <ArrowDown size={13} />
                        </button>
                        <button
                          onClick={() => handleDeleteStep(step.id)}
                          title="删除"
                          style={{
                            background: 'none', border: 'none', cursor: 'pointer',
                            color: 'var(--accent-error)', padding: '3px 5px', borderRadius: 4,
                          }}
                        >
                          <Trash2 size={13} />
                        </button>
                      </div>
                    </div>
                  )
                })}
              </>
            )}
          </div>
        </div>

        {/* ----- 右侧：脚本预览 + 输出 ----- */}
        <div style={{ width: 360, display: 'flex', flexDirection: 'column', gap: 10, overflow: 'hidden' }}>

          {/* 脚本预览 */}
          <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
            <div style={{ 
              fontSize: 11, 
              color: 'var(--text-muted)', 
              marginBottom: 6, 
              fontWeight: 600, 
              letterSpacing: 1,
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
            }}>
              <span>SHELL 脚本预览 {enableLoop && <span style={{ color: 'var(--accent-primary)', fontSize: 10 }}>（循环模式）</span>}</span>
              <span style={{ fontSize: 10, fontWeight: 400 }}>
                {steps.filter(s => s.enabled).length} / {steps.length} 步骤已启用
              </span>
            </div>
            <div style={{
              flex: 1,
              background: 'var(--bg-card)',
              border: '1px solid var(--border-color)',
              borderRadius: 8,
              overflow: 'hidden',
              position: 'relative',
              display: 'flex',
              flexDirection: 'column',
            }}>
              {/* 行号 + 代码 */}
              <div style={{
                display: 'flex',
                flex: 1,
                overflow: 'auto',
                fontFamily: "'Cascadia Code', 'Consolas', monospace",
                fontSize: 11,
                lineHeight: '1.6',
              }}>
                {/* 行号列 */}
                <div style={{
                  padding: '10px 8px',
                  background: 'var(--bg-secondary)',
                  color: 'var(--text-muted)',
                  textAlign: 'right',
                  userSelect: 'none',
                  borderRight: '1px solid var(--border-color)',
                  minWidth: 35,
                  flexShrink: 0,
                }}>
                  {scriptPreview.split('\n').map((_, i) => (
                    <div key={i} style={{ height: '17.6px' }}>{i + 1}</div>
                  ))}
                </div>
                {/* 代码列 */}
                <pre style={{
                  flex: 1,
                  background: 'transparent',
                  border: 'none',
                  color: 'var(--accent-secondary)',
                  fontFamily: "'Cascadia Code', 'Consolas', monospace",
                  fontSize: 11,
                  lineHeight: '1.6',
                  padding: '10px 12px',
                  margin: 0,
                  whiteSpace: 'pre-wrap',
                  wordBreak: 'break-word',
                }}>{scriptPreview}</pre>
              </div>
            </div>
          </div>

          {/* 执行输出 */}
          <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minHeight: 0 }}>
            <div style={{
              fontSize: 11, color: 'var(--text-muted)', marginBottom: 6, fontWeight: 600, letterSpacing: 1,
              display: 'flex', alignItems: 'center', gap: 6, justifyContent: 'space-between',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                {isRunning && <Loader size={11} className="spinning" style={{ color: 'var(--accent-primary)' }} />}
                执行输出 {isRunning && <span style={{ color: 'var(--accent-primary)' }}>(运行中...)</span>}
              </div>
              
              {/* 过滤和搜索工具栏 */}
              <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
                {/* 搜索框 */}
                <input
                  type="text"
                  placeholder="搜索输出..."
                  value={outputSearch}
                  onChange={e => setOutputSearch(e.target.value)}
                  style={{
                    background: 'var(--bg-secondary)',
                    border: '1px solid var(--border-color)',
                    borderRadius: 4,
                    color: 'var(--text-primary)',
                    padding: '3px 8px',
                    fontSize: 10,
                    width: 100,
                    outline: 'none',
                  }}
                />
                
                {/* 过滤器 */}
                <select
                  value={outputFilter}
                  onChange={e => setOutputFilter(e.target.value as any)}
                  style={{
                    background: 'var(--bg-secondary)',
                    border: '1px solid var(--border-color)',
                    borderRadius: 4,
                    color: 'var(--text-primary)',
                    padding: '3px 6px',
                    fontSize: 10,
                    outline: 'none',
                    cursor: 'pointer',
                  }}
                >
                  <option value="all">全部</option>
                  <option value="error">仅错误</option>
                  <option value="success">仅成功</option>
                </select>
              </div>
            </div>
            <div style={{
              flex: 1,
              background: '#0d0d0d',
              border: '1px solid var(--border-color)',
              borderRadius: 8,
              padding: '8px 10px',
              overflow: 'auto',
              fontFamily: "'Cascadia Code', 'Consolas', monospace",
              fontSize: 11,
              lineHeight: 1.7,
              minHeight: 0,
            }}>
              {(() => {
                // 应用过滤和搜索
                let filtered = output
                if (outputFilter !== 'all') {
                  filtered = filtered.filter(line => line.type === outputFilter)
                }
                if (outputSearch) {
                  filtered = filtered.filter(line => 
                    line.text.toLowerCase().includes(outputSearch.toLowerCase())
                  )
                }
                
                return filtered.length === 0 ? (
                  <span style={{ color: 'var(--text-muted)' }}>
                    {output.length === 0 ? '运行后将显示输出...' : '没有匹配的输出了'}
                  </span>
                ) : (
                  filtered.map((line, i) => {
                    const timeStr = new Date(line.timestamp).toLocaleTimeString('zh-CN', { hour12: false })
                    let color = 'var(--text-secondary)'
                    if (line.type === 'error') color = 'var(--accent-error)'
                    else if (line.type === 'success') color = 'var(--accent-success)'
                    
                    // 高亮搜索关键词
                    let displayText = line.text
                    if (outputSearch) {
                      const regex = new RegExp(`(${outputSearch})`, 'gi')
                      displayText = line.text.replace(regex, '<mark>$1</mark>')
                    }
                    
                    return (
                      <div key={i} style={{ color, fontFamily: 'monospace', fontSize: 11 }}>
                        <span style={{ color: 'var(--text-muted)', marginRight: 8 }}>[{timeStr}]</span>
                        <span dangerouslySetInnerHTML={{ __html: displayText }} />
                      </div>
                    )
                  })
                )
              })()}
              <div ref={outputEndRef} />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
